core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import core.views as coreviews

urlpatterns = patterns('',

 url(r'^$', coreviews.LandingView.as_view()),
 url(r'robot/$', coreviews.RobotListView.as_view()),
 url(r'robot/(?P<pk>\d+)/detail/$', coreviews.DetailListView.as_view(), name='robot_list'),
 url(r'robot/create/$', coreviews.RobotCreateView.as_view()),
 url(r'search/$', coreviews.SearchListView.as_view()),
 url(r'robot/(?P<pk>\d+)/update/$', coreviews.RobotUpdateView.as_view(), name='robot_update'),
 url(r'robot/(?P<pk>\d+)/delete/$', coreviews.RobotDeleteView.as_view(), name='delete'),
)

django_ch/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from core.views import RobotDeleteView
import core.views as coreviews


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', coreviews.LandingView.as_view()),
    url(r'robot/$', coreviews.RobotListView.as_view(), name='list'),
    url(r'robot/(?P<pk>\d+)/detail/$', coreviews.DetailListView.as_view(), name='robot_list'),
    url(r'robot/create/$', coreviews.RobotCreateView.as_view()),
    url(r'search/$', coreviews.SearchListView.as_view()),
    url(r'robot/(?P<pk>\d+)/update/$', coreviews.RobotUpdateView.as_view(), name='robot_update'),
    url(r'robot/(?P<pk>\d+)/delete/$', coreviews.RobotDeleteView.as_view(), name='delete'),
]

core/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


import os
import uuid


RATING_CHOICES = (
    (0, 'None'),
    (1, 'weak'),
    (2, 'fair'),
    (3, 'standard'),
    (4, 'strong'),
    (5, 'exclusive'),
    )

MULTI_CHOICES = (
    (0, '1'),
    (1, '2'),
    (2, '3'),
    (3, '4'),
    (4, '5'),
    (5, '6+'),
    )

SPEED_CHOICES = (
    (0, 'constant speed'),
    (1, 'can accelerate')
    )

PLURAL_CHOICES = (
    (0, 'none'),
    (1, 'minimal'),
    (2, 'some'),
    (3, 'ample')
    )

YESNO_CHOICES = (
    (0, 'No'),
    (1, 'Yes'),
    )


# Create your models here.
class Robot(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    axles = models.IntegerField(choices=MULTI_CHOICES, null=True, blank=True)
    motionrange = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    speed = models.IntegerField(choices=SPEED_CHOICES, null=True, blank=True)
    repeatability = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    payload = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    mass = models.IntegerField(choices=MULTI_CHOICES, null=True, blank=True)
    vreach = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)
    hreach = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)
    structure = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(viewname="robot_list", args=[self.id])

    def get_reviews(self):
        return self.review_set.all()

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from core.models import Robot
import core.models as coremodels

# Create your views here.

class LandingView(TemplateView):
    template_name = 'base/index.html'

class RobotListView(ListView):
    model = coremodels.Robot
    template_name = 'robot/list.html'

class DetailListView(DetailView):
    model = coremodels.Robot
    template_name = 'robot/detail.html'
    context_object_name = 'robot'

class RobotCreateView(CreateView):
    model = coremodels.Robot
    template_name = 'base/form.html'
    fields = "__all__"

class RobotUpdateView(UpdateView):
    model = coremodels.Robot
    template_name = 'base/form.html'
    fields = "__all__"

class RobotDeleteView(DeleteView):
    model = coremodels.Robot
    template_name = 'robot/delete.html'
    context_object_name = 'item'
    success_url = reverse_lazy('list')

class SearchListView(RobotListView):
    def get_queryset(self):
        incoming_query_string = self.request.GET.get('query', '')
        return coremodels.Robot.objects.filter(name__icontains=incoming_query_string)

templates/base/form.html
{% extends "robot/detail.html" %}
{% load widget_tweaks %}
<!DOCTYPE html>
{% block content %}
    <section>
        <div>
            <h1><a href="/">R|T R A C K E R</a></h1>
            <nav>
                <a href="/robot">BACK TO THE FUTURE</a>
            </nav>
            <div>
                {% if form %}
                <div class="create-form">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}{{ form.media }}
                        {% for field in form %}
                        <div>
                            <label for="exampleInputFile">{{ field.label }}</label>
                            {{ field|add_class:"form-control"}}
                            {% if field.help_text %}
                            <p class="help-block">{{ field.help_text }}</p>
                            {% endif %}
                        </div>
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <div id="error_{{ field.name }}">{{ error|escape }}</div>
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                        <button><input class="create-submit" type="submit" class="btn btn-success"role="button" value="{{ verb|default:"Submit" }}" /></button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </section>
    {% endblock %}

templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>R|T R A C K E R</title>
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>
    <body>
        <h1><a href="/">R|T R A C K E R</a></h1>
        <a href="/robot">ROBOT LIST</a>
        {% block search %}
        <form action="/search/" class="navbar-form navbar-right" method="get">
            <input type="text" placeholder="...or search letter or name here" class="form-control" name="query"></input>
        </form>
        {% endblock %}
        <p>We track robots! You can add, edit, or delete them.</p>
    </body>
</html>

templates/robot/delete.html
{% load staticfiles %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>R T R A C K E R</title>
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>
    <body>
        <form action="" method="post">
            {% csrf_token %}
            <p class="confirm">Are you sure you want to delete this robot?</p>
            <input type="submit" value="Delete"/>
        </form>
        <a href="/robot">Cancel</a>
    </body>
</html>

templates/robot/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>R|T R A C K E R</title>
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>
    {% block content %}
    <h1><a href="/">R|T R A C K E R</a></h1>

    <nav>
        <a href="/robot">BACK TO THE FUTURE</a>
    </nav>
    <div class="list">
        <h3>{{ robot.name }}</h3>
        {% if robot.description %}
        <p>{{ robot.description }}</p>
        {% endif %}
        <p><b>Axles: </b>{% if robot.axles %}{{ robot.get_axles_display }}{% else %}----{% endif %}</p>

        <p><b> Motion Range: </b>{% if robot.motionrange %}{{ robot.get_motionrange_display }}{% else %}----{% endif %}</p>
        <p><b> Speed: </b>{% if robot.speed %}{{ robot.get_speed_display }}{% else %}----{% endif %}</p>
        <p><b> Repeatability: </b>{% if robot.repeatability %}{{ robot.get_repeatability_diplay }}{% else %}----{% endif %}</p>
        <p><b> Payload: </b>{% if robot.payload %}{{ robot.get_payload_display }}{% else %}----{% endif %}</p>
        <p><b> Mass: </b>{% if robot.mass %}{{ robot.get_mass_display }}{% else %}----{% endif %}</p>
        <p><b> V-Reach </b>{% if robot.vreach %}{{ robot.get_vreach_display }}{% else %}----{% endif %}</p>
        <p><b> H-Reach </b>{% if robot.hreach %}{{ robot.get_hreach_display }}{% else %}----{% endif %}</p>
        <p><b> Structure </b>{% if robot.structure %}{{ robot.get_structure_display }}{% else %}----{% endif %}</p>
        <button><a href="{% url 'robot_update' pk=robot.id %}">Edit</a></button>
    </div>
    {% endblock %}

templates/robot/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>R|T R A C K E R</title>
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>
    {% block content %}
    <h1><a href="/">R|T R A C K E R</a></h1>
    <h4><a href="/robot/create/">CREATE A ROBOT</a></h4>
    {% block search %}
    <form action="/search/" class="navbar-form navbar-right" method="get">
        <input type="text" placeholder="search robot letter or name here" class="form-control" name="query"></input>
    </form>
    {% endblock %}
    {% endblock %}
    {% for robot in robot_list %}
    <div class="list">
        <h3><a href="{{ robot.get_absolute_url }}">{{ robot.name }}</a></h3>
        {% if robot.description %}
        <p>{{ robot.description }}</p>
        {% endif %}
        <p><b>Axles: </b>{% if robot.axles %}{{ robot.get_axles_display }}{% else %}----{% endif %}</p>

        <p><b> Motion Range: </b>{% if robot.motionrange %}{{ robot.get_motionrange_display }}{% else %}----{% endif %}</p>
        <p><b> Speed: </b>{% if robot.speed %}{{ robot.get_speed_display }}{% else %}----{% endif %}</p>
        <p><b> Repeatability: </b>{% if robot.repeatability %}{{ robot.get_repeatability_display }}{% else %}----{% endif %}</p>
        <p><b> Payload: </b>{% if robot.payload %}{{ robot.get_payload_display }}{% else %}----{% endif %}</p>
        <p><b> Mass: </b>{% if robot.mass %}{{ robot.get_mass_display }}{% else %}----{% endif %}</p>
        <p><b> V-Reach </b>{% if robot.vreach %}{{ robot.get_vreach_display }}{% else %}----{% endif %}</p>
        <p><b> H-Reach </b>{% if robot.hreach %}{{ robot.get_hreach_display }}{% else %}----{% endif %}</p>
        <p><b> Structure </b>{% if robot.structure %}{{ robot.get_structure_display }}{% else %}----{% endif %}</p>
        <button><a href="{% url 'delete' pk=robot.id %}">Delete</a></button>
    </div>
    {% endfor %}